CI/CD
* added integration tests to ci/cd
* refactored dockerfile and docker-compose.yml
* refactored docker-compose.yml
* optimized integration tests run - now it uses only one container and executes one by one

diff --git a/docker/integration/tests/Dockerfile b/docker/integration/tests/Dockerfile
--- a/docker/integration/tests/Dockerfile
+++ b/docker/integration/tests/Dockerfile
@@ -1,26 +1,38 @@
-FROM ubuntu:22.04
+FROM golang:1.21.1-bookworm
 
-ARG GOOS=linux
-ARG GOARCH=amd64
 ARG DEBIAN_FRONTEND=noninteractive
 
-RUN apt-get update && apt-get install -y wget gnupg2
-RUN echo "deb https://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list
-RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
-RUN apt-get update && apt-get install --yes --no-install-recommends --no-install-suggests  \
-    postgresql-16 \
-    postgresql-15 \
-    postgresql-14 \
-    postgresql-13 \
-    postgresql-12 \
-    postgresql-11
-RUN wget https://go.dev/dl/go1.21.1.linux-amd64.tar.gz && \
-    rm -rf /usr/local/go &&  \
-    tar -C /usr/local -xzf go1.21.1.linux-amd64.tar.gz
+RUN apt-get update && apt-get install -y wget gnupg2 lsb-release make \
+    && echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
+    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
+    && apt-get update && apt-get install --yes --no-install-recommends --no-install-suggests  \
+        postgresql-16 \
+        postgresql-15 \
+        postgresql-14 \
+        postgresql-13 \
+        postgresql-12 \
+        postgresql-11
 
-RUN mkdir /var/lib/greenmask && cd /var/lib/greenmask
 WORKDIR /var/lib/greenmask
-COPY . .
-RUN cd cmd/greenmask && /usr/local/go/bin/go build . && cd -
 
-CMD ["sh", "-c", "/usr/local/go/bin/go test -v ./tests/integration/..."]
+COPY . .
+
+RUN make build \
+    && echo '#!/bin/bash \n\
+IFS="," read -ra PG_VERSIONS_CHECK <<< "${PG_VERSIONS_CHECK}" \n\
+for pg_version in ${PG_VERSIONS_CHECK[@]}; do \n\
+    echo "### CHECK COMPATIBILITY WITH POSTGRESQL ${pg_version} ###" \n\
+    export PG_HOST=$(echo "${PG_HOST_TEMPLATE}" | sed "s/<version>/${pg_version}/") \n\
+    export STORAGE_S3_PREFIX="${pg_version}" \n\
+    export URI="host=${PG_HOST} user=${PG_USER} password=${PG_PASSWORD} dbname=${PG_DATABASE} port=${PG_PORT}" \n\
+    export PG_BIN_PATH="/usr/lib/postgresql/${pg_version}/bin/" \n\
+    go test -v ./tests/integration/... \n\
+    if [ $? -eq 0 ]; then \n\
+        echo "### SUCCESSFUL CHECK COMPATIBILITY WITH POSTGRESQL ${pg_version} ###" \n\
+    else \n\
+        echo "### FAIL CHECK COMPATIBILITY WITH POSTGRESQL ${pg_version} ###" \n\
+    fi \n\
+done \n' > /docker-entrypoint.sh \
+    && chmod +x /docker-entrypoint.sh
+
+CMD ["bash", "-c", "/docker-entrypoint.sh"]
